[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "lxml>=6.0.2",
]

[project.scripts]
nk = "nk.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/nk"]

[tool.hatch.envs.default]
path = ".venv"
